spi:
  clk_pin: 18
  mosi_pin: 23
  interface: hardware

spi_device:
  cs_pin: 5
  data_rate: 20MHz
  mode: 3
  bit_order: msb_first


font:
  - file: "gfonts://Material+Symbols+Outlined"
    glyphs: ["\U0000e425"] # mdi-timer
    id: my_font
    size: 20
    bpp: 2

color:
  - id: my_color_font
    red: 0%
    green: 0%
    blue: 0%

  - id: my_color_back
    red: 100%
    green: 0%
    blue: 100%


# Example minimal configuration entry
display:
- platform: ili9xxx
  model: ILI9488
  dc_pin: 16
  reset_pin: 17 
  dimensions: 
    height: 480
    width: 320
  rotation: 0

  lambda: 
    it.fill(id(my_color_back));
    it.print(50, 50, id(my_font), id(my_color_font), TextAlign::TOP_LEFT, "Hello World!");